In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
data=pd.read_csv("Breast_cancer_data.csv")

df=pd.DataFrame(data)

df

mean_radius  mean_texture  mean_perimeter  mean_area  mean_smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     diagnosis  
0            0  
1            0  
2            0  
3            0  
4            0  
..         ...  
564          0  
565          0  
566          0  
567          0  
568          1  

[569 rows x 6 columns]

In [6]:
from sklearn.model_selection import train_test_split

x = df.drop(['diagnosis'], axis=1)
y = df['diagnosis']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)


In [7]:
#1) KNN Classifier

In [8]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train, y_train)
y_predict_1 = knn.predict(x_test)
y_predict_1

array([1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1], dtype=int64)

In [9]:
#2) Decision Tree 

In [10]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()

model.fit(x_train,y_train)

y_predict_2 = model.predict(x_test)

print(y_predict_2)

#metrics.accuracy_score(y_predict,y_test)


[1 1 0 1 1 1 1 0 1 1 1 0 1 1 0 1 0 0 1 0 0 1 0 0 1 1 1 1 0 0 0 1 1 0 1 1 0
 1 0 1 1 1 0 1 1 0 0 0 0 1 1 0 1 0 1 1 0 1 1 0 1 1 0 0 1 1 1 1 1 0 1 1 0 0
 0 1 1 1 1 0 1 0 1 1 0 1 1 0 1 1 0 1 0 1 0 1 1 0 0 1 0 1 1 1 0 1 0 0 1 1 0
 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 1 1 0 0 1 1 0 0 0 0 0 1 1
 1 0 1 0 0 1 1 1 0 1 0 0 0 1 0 0 1 1 1 1 1 1 0]


In [11]:
#3)SVC
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100)
rf.fit(x_train, y_train)
y_predict_3 = rf.predict(x_test)
y_predict_3


array([1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0], dtype=int64)

In [15]:
#Acuuracies
from sklearn import metrics

In [16]:
print("Accuracy of K Neartest Neighbours : ",end=" ")
print(metrics.accuracy_score(y_predict_1,y_test))

print("Accuracy of Decision Tress : ",end=" ")
print(metrics.accuracy_score(y_predict_2,y_test))

print("Accuracy of Random Forest : ",end=" ")
print(metrics.accuracy_score(y_predict_3,y_test))



Accuracy of K Neartest Neighbours :  0.8713450292397661
Accuracy of Decision Tress :  0.8713450292397661
Accuracy of Random Forest :  0.9064327485380117


In [18]:
#KNN Cross Validation
from sklearn import model_selection
kfold = model_selection.KFold(n_splits = 3)
tr=KNeighborsClassifier(n_neighbors=5)
tr1 = DecisionTreeClassifier()
tr2=RandomForestClassifier(n_estimators=100)

tr.fit(x_train, y_train)
results = model_selection.cross_val_score(tr, x_train, y_train, cv = kfold)
print("results for KNN: ")
print(results)
print("")


tr1.fit(x_train, y_train)
results1 = model_selection.cross_val_score(tr1, x_train, y_train, cv = kfold)
print("results for Decision Tree: ")
print(results1)
print("")


tr2.fit(x_train, y_train)
results2 = model_selection.cross_val_score(tr2, x_train, y_train, cv = kfold)
print("results for Random Forest: ")
print(results2)
print("")


results for KNN: 
[0.85714286 0.84210526 0.84848485]

results for Decision Tree: 
[0.85714286 0.86466165 0.88636364]

results for Random Forest: 
[0.91729323 0.87218045 0.91666667]



In [20]:
val=0
val1=0
val2=0
for i in range(3):
    val+=results[i]
    val1+=results1[i]
    val2+=results2[i]

print(val/3)
print(val1/3)
print(val2/3)


0.8492443229285335
0.8693893825472773
0.9020467836257309


In [ ]:
#There fore Random Forest is the best clasifier